import { describe, it, expect, vi, beforeEach } from 'vitest';
import { renderHook, act } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { createElement } from 'react';
import { useHockeyTeams } from '../useHockeyTeams';
vi.mock('@sudobility/sports_api_client', () => ({ useHockeyTeams: vi.fn() }));
vi.mock('@sudobility/heavymath_indexer_client', () => ({ useFavorites: vi.fn() }));
import { useHockeyTeams as useApi } from '@sudobility/sports_api_client';
import { useFavorites } from '@sudobility/heavymath_indexer_client';
const mockUseApi = vi.mocked(useApi);
const mockUseFavorites = vi.mocked(useFavorites);
const mockData = [{ id: 10, name: 'Bruins' }, { id: 20, name: 'Rangers' }];
const mockFavs = [{ id: 1, itemId: '10', category: 'sports', subcategory: 'hockey', type: 'team' }];
const ic = {} as any; const wa = '0xabc';
const cw = () => { const qc = new QueryClient({ defaultOptions: { queries: { retry: false } } }); return ({ children }: { children: React.ReactNode }) => createElement(QueryClientProvider, { client: qc }, children); };
describe('useHockeyTeams', () => {
  beforeEach(() => { vi.clearAllMocks(); mockUseApi.mockReturnValue({ data: { response: mockData, results: 2, paging: { current: 1, total: 1 } }, isLoading: false, isError: false, error: null } as any); mockUseFavorites.mockReturnValue({ favorites: mockFavs, isLoading: false, isError: false, error: null, addFavorite: { mutateAsync: vi.fn(), isPending: false }, removeFavorite: { mutateAsync: vi.fn(), isPending: false }, refresh: vi.fn() } as any); });
  it('should return teams with favorited flag', () => { const { result } = renderHook(() => useHockeyTeams(ic, wa), { wrapper: cw() }); expect(result.current.teams).toHaveLength(2); expect(result.current.teams[0].favorited).toBe(true); expect(result.current.teams[1].favorited).toBe(false); });
  it('should call addFavorite', async () => { const m = vi.fn().mockResolvedValue({}); mockUseFavorites.mockReturnValue({ favorites: [], isLoading: false, isError: false, error: null, addFavorite: { mutateAsync: m, isPending: false }, removeFavorite: { mutateAsync: vi.fn(), isPending: false }, refresh: vi.fn() } as any); const { result } = renderHook(() => useHockeyTeams(ic, wa), { wrapper: cw() }); await act(async () => { await result.current.setFavorited(10, true); }); expect(m).toHaveBeenCalledWith({ category: 'sports', subcategory: 'hockey', type: 'team', id: '10' }); });
  it('should pass correct filters', () => { renderHook(() => useHockeyTeams(ic, wa), { wrapper: cw() }); expect(mockUseFavorites).toHaveBeenCalledWith(ic, wa, { category: 'sports', subcategory: 'hockey', type: 'team' }); });
  it('should return empty when undefined', () => { mockUseApi.mockReturnValue({ data: undefined, isLoading: false, isError: false, error: null } as any); const { result } = renderHook(() => useHockeyTeams(ic, wa), { wrapper: cw() }); expect(result.current.teams).toHaveLength(0); });
});
